apiVersion : apps/v1
kind: Deployment
metadata:
  name: sivaanbalagannodesamples 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sivaanbalagannodesamples
  template:
    metadata:
      labels:
        app: sivaanbalagannodesamples 
    spec:
      containers:
        - name: sivaanbalagannodesamples 
          image: aacloudrn.azurecr.io/sivaanbalagannodesamples
          ports:
          - containerPort: 8080/tcp